name: C++ CI - Build and Run Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    # Шаг 1: Получение кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Шаг 2: Настройка инструментов сборки Visual Studio
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    # Шаг 3: Вывод информации о проекте (для отладки)
    - name: Project Structure
      run: |
        echo "=== СТРУКТУРА ПРОЕКТА ==="
        echo "Файлы в корне:"
        Get-ChildItem
        echo ""
        echo "Solution файлы:"
        Get-ChildItem -Filter "*.sln"
        echo ""
        echo "Файлы проектов:"
        Get-ChildItem -Recurse -Filter "*.vcxproj" | Format-Table Name, Directory
      
    # Шаг 4: Восстановление NuGet пакетов
    - name: Restore NuGet Packages
      run: |
        echo "=== ВОССТАНОВЛЕНИЕ NUGET ПАКЕТОВ ==="
        if (Test-Path "packages.config") {
          nuget restore
        } else {
          echo "Файл packages.config не найден, пропускаем восстановление"
        }
      
    # Шаг 5: Сборка решения
    - name: Build Solution
      run: |
        echo "=== СБОРКА РЕШЕНИЯ ==="
        msbuild TestingSystem.sln /p:Configuration=Release /p:Platform=x64 /p:RestorePackages=false /verbosity:minimal
      
    # Шаг 6: Поиск собранных тестов
    - name: Find Test Executable
      run: |
        echo "=== ПОИСК ИСПОЛНЯЕМОГО ФАЙЛА ТЕСТОВ ==="
        echo "Рекурсивный поиск Tests.exe:"
        Get-ChildItem -Recurse -Filter "Tests.exe" | Format-Table FullName
        echo ""
        echo "Все .exe файлы:"
        Get-ChildItem -Recurse -Filter "*.exe" | Format-Table Name, Directory
        echo ""
        echo "Содержимое ключевых папок:"
        if (Test-Path "Tests") {
          echo "Папка Tests:"
          Get-ChildItem "Tests" -Recurse | Format-Table Name
        }
        if (Test-Path "x64") {
          echo "Папка x64:"
          Get-ChildItem "x64" -Recurse | Format-Table Name
        }
      
    # Шаг 7: Запуск модульных тестов
    - name: Run Unit Tests
      run: |
        echo "=== ЗАПУСК МОДУЛЬНЫХ ТЕСТОВ ==="
        
        # Определяем путь к тестам
        $testPath = $null
        
        if (Test-Path "Tests\x64\Release\Tests.exe") {
          $testPath = "Tests\x64\Release\Tests.exe"
        } elseif (Test-Path "x64\Release\Tests\Tests.exe") {
          $testPath = "x64\Release\Tests\Tests.exe"
        } elseif (Test-Path "Tests\Tests.exe") {
          $testPath = "Tests\Tests.exe"
        } else {
          # Пробуем найти любой Tests.exe
          $foundTests = Get-ChildItem -Recurse -Filter "Tests.exe" | Select-Object -First 1
          if ($foundTests) {
            $testPath = $foundTests.FullName
          }
        }
        
        if ($testPath) {
          echo "✅ Найден Tests.exe: $testPath"
          echo "Запуск тестов..."
          & $testPath
          $exitCode = $LASTEXITCODE
          if ($exitCode -eq 0) {
            echo "✅ Тесты выполнены успешно!"
          } else {
            echo "❌ Тесты завершились с ошибкой (код: $exitCode)"
            exit $exitCode
          }
        } else {
          echo "❌ Файл Tests.exe не найден!"
          echo "Доступные .exe файлы:"
          Get-ChildItem -Recurse -Filter "*.exe" | Format-Table FullName
          exit 1
        }
      
    # Шаг 8: Финальный результат
    - name: Test Completion
      run: |
        echo ""
        echo "🎉 =============================== 🎉"
        echo "✅ ВСЕ ТЕСТЫ УСПЕШНО ЗАВЕРШЕНЫ!"
        echo "✅ CI/CD НАСТРОЕН КОРРЕКТНО!"
        echo "🎉 =============================== 🎉"